[build]
  publish = "."
  command = "./precompress.sh || true"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/wasm/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/wasm"

[[headers]]
  for = "/assets.epw"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/*.epw"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/*.epk"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"
